/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "TIMER.h"
#include "PWM.h"
#include "Clock_1.h"
#include "motor_aliases.h"
#include "motor.h"
#include "HE_aliases.h"
#include "HE.h"
#include "HE_ISR.h"
#include "UART.h"
#include "SERVO_aliases.h"
#include "SERVO.h"
#include "RAW_VIDEO_aliases.h"
#include "RAW_VIDEO.h"
#include "Clock_2.h"
#include "CSYNC_IN_aliases.h"
#include "CSYNC_IN.h"
#include "VSYNC_IN_aliases.h"
#include "VSYNC_IN.h"
#include "SERVO_PWM.h"
#include "COMP.h"
#include "VDAC.h"
#include "VID_TIMER.h"
#include "INT_SAMPLE.h"
#include "Clock_3.h"
#include "DEBUG_2_aliases.h"
#include "DEBUG_2.h"
#include "DEBUG_3_aliases.h"
#include "DEBUG_3.h"
#include "DEBUG_4_aliases.h"
#include "DEBUG_4.h"
#include "DEBUG_5_aliases.h"
#include "DEBUG_5.h"
#include "DEBUG_1_aliases.h"
#include "DEBUG_1.h"
#include "DEBUG_6_aliases.h"
#include "DEBUG_6.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

